SELECT
	S.STUDENT_NUMBER,
	SDA.ATT_DATE,
	SCH.NAME,
	PE.GRADE_LEVEL,
	S.ETHNICITY,
	S.GENDER,
	SDA.ATT_CODE 
FROM
	PS.PS_ENROLLMENT PE JOIN PS.STUDENTS S ON PE.STUDENTID = S.ID JOIN PS.SCHOOLS SCH ON PE.SCHOOLID = SCH.SCHOOL_NUMBER 
	JOIN ((
SELECT
	STUDENTID,
	SCHOOLID,
	ATT_CODE,
	ATT_DATE 
FROM
	( PS.PS_ATTENDANCE_MEETING )) UNION ALL
	(
SELECT
	STUDENTID,
	SCHOOLID,
	ATT_CODE,
	ATT_DATE 
FROM
	( PS.PS_ATTENDANCE_INTERVAL )) UNION ALL
	(
SELECT
	STUDENTID,
	SCHOOLID,
	ATT_CODE,
	ATT_DATE 
FROM
	( PS.PS_ATTENDANCE_DAILY ))) SDA ON PE.STUDENTID = SDA.STUDENTID 
WHERE
	PE.ENTRYDATE BETWEEN TO_DATE( '08/1/2011', 'mm/dd/yyyy' ) 
	AND TO_DATE( '07/31/2017', 'mm/dd/yyyy' ) 
	and SDA.ATT_DATE BETWEEN TO_DATE( '08/1/2011', 'mm/dd/yyyy' ) 
	AND TO_DATE( '07/31/2017', 'mm/dd/yyyy' ) 
	AND PE.EXITDATE > PE.ENTRYDATE 
	AND SDA.ATT_CODE IN ( 'A', 'I', 'E', 'U', 'M', 'K' ) /*AND SDA.PRESENCE_STATUS_CD = 'Absent'*/
	AND PE.SCHOOLID BETWEEN 103 
	AND 166 
	AND PE.SCHOOLID NOT IN ( 108, 156 ) 
	AND PE.GRADE_LEVEL BETWEEN 0 
	AND 6 
ORDER BY
SDA.ATT_DATE